### PR TITLE
[KNI] Bump scheduler-plugins to use NRT API v0.12

### PR DESCRIPTION
**Pull request by Tal-or**
```
git remote add k8ssigstream https://github.com/kubernetes-sigs/scheduler-plugins.git
git fetch -v -p --all
git checkout master
git checkout -b bump_nrt_to_v0.12
git merge k8ssigstream/master
# fix conflicts introduced by kni-local changes
# send PR for review
```
Integration test and unit test passed locally

### CODE REVIEW

**Comment by ffromani** [comment]
I'm surprised we can't do just a trivial git merge. How was this PR generated?

**Comment by Tal-or** [comment]
> I'm surprised we can't do just a trivial git merge. How was this PR generated?

I rebased from ```k8s-sigs/scheduler-plugins``` and fixed the gaps (like the in the unittests) that are kni-specific.

What do you mean by git merge? usually, we're using rebase and not merge since it messes up the commits` authors

**Comment by ffromani** [comment]
> > I'm surprised we can't do just a trivial git merge. How was this PR generated?
> 
> I rebased from `k8s-sigs/scheduler-plugins` and fixed the gaps (like the in the unittests) that are kni-specific.
> 
> What do you mean by git merge? usually, we're using rebase and not merge since it messes up the commits` authors

I can't recall how git merge messes up the commit's author. In this case I'm not sure rebase is the right call, let's evaluate

**Comment by Tal-or** [comment]
> > > I'm surprised we can't do just a trivial git merge. How was this PR generated?
> > 
> > 
> > I rebased from `k8s-sigs/scheduler-plugins` and fixed the gaps (like the in the unittests) that are kni-specific.
> > What do you mean by git merge? usually, we're using rebase and not merge since it messes up the commits` authors
> 
> I can't recall how git merge messes up the commit's author. In this case I'm not sure rebase is the right call, let's evaluate

I wonder why merge is the right approach here. not disagree - just curious 
Anyway, merged as you asked

**Comment by ffromani** [comment]
> > > > I'm surprised we can't do just a trivial git merge. How was this PR generated?
> > > 
> > > 
> > > I rebased from `k8s-sigs/scheduler-plugins` and fixed the gaps (like the in the unittests) that are kni-specific.
> > > What do you mean by git merge? usually, we're using rebase and not merge since it messes up the commits` authors
> > 
> > 
> > I can't recall how git merge messes up the commit's author. In this case I'm not sure rebase is the right call, let's evaluate
> 
> I wonder why merge is the right approach here. not disagree - just curious Anyway, merged as you asked

It depends. The goals in our case are:

0. NEVER EVER rewrite history
1. preserve u/s history verbatim (no commit rewrite)
2. have a crystal clear distinction between u/s changes (verbatim) and local changes for our case
3. make the flow as cheap as possible maintenance wise

the merge flow seems to tick all the boxes (it's what github automates to resync a fork anyway).
a rebase flow COULD be also fine, provided the steps are documented (xref: https://github.com/openshift-kni/scheduler-plugins/pull/13) and the goals above are met.

EDIT: so, provided we have clear steps for rebase flow, I don't mind nor have strong preferences. Thing is: I do have the steps for merge, not for rebase :)

last but not least, in order to fullfill requirement 2 above, please add a `[KNI]` tag to all commit messages of changes specific to this repo (e.g. https://github.com/openshift-kni/scheduler-plugins/pull/12/commits/8f5b20d67ef1b5e01f713f9d54e1d26601d8c47a )

**Comment by ffromani** [comment]
thanks. LGTM.
In a followup PR: please create a README in this repo documenting how we will sync with u/s, e.g. the  flow (merge vs rebase) we discussed. https://github.com/openshift-kni/scheduler-plugins/pull/12#issuecomment-979250893 could be a starting point.
If you want to propose a rebase flow, I have no objections provided our goals are met.

**Comment by Tal-or** [comment]
> thanks. LGTM. In a followup PR: please create a README in this repo documenting how we will sync with u/s, e.g. the flow (merge vs rebase) we discussed. [#12 (comment)](https://github.com/openshift-kni/scheduler-plugins/pull/12#issuecomment-979250893) could be a starting point. If you want to propose a rebase flow, I have no objections provided our goals are met.

Just saw this comment. will work on it tomorrow

**Pull request merged**
